# ================== SALESFORCE AUTH ==================
salesforce.instance.url=https://test.salesforce.com
salesforce.api.version=v61.0

salesforce.username=vishnuroyal216.f5bc9215a43d@agentforce.com
salesforce.password=Manasa@12XeL6v4KaSmhe3qzA4CIfKcC

salesforce.client.id=3MVG9JwBBbcN47LUkNHU9cGUgbGq3ZAVvMbmEfEqVyp_S4DPBvlkba92muanZzE.WnlpmXce9mLDJv7LW2.T
salesforce.client.secret=7BFF8DE5E13C0C155923521931D473CAD2858E42CA5468BCABA81BBD4B93323E

server.port=9055
spring.mvc.cors.allowed-origins=http://localhost:3000